### ISSUE TITLE
Pre-trained models link are not available

### ISSUE THREAD

**Issue by izmcm** [mhwong2007/Deep-Packet#3]
Hi! First, thank you very much for this implementation :D  
I'm trying download the pre-trained models but the link is not working :( The drive shows "The file you requested does not exist.".

**Comment by mhwong2007** [comment]
Hi!

I updated the link :D

https://drive.google.com/file/d/1UgSqcN5SG5hqC2imlYu6bB2f9jD1iiu8/view?usp=sharing
